services:
  nexus:
    image: sonatype/nexus3:3.76.0-ubi
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
  # ssh-agent:
  #   image: jenkins/ssh-agent
volumes:
  nexus-data:
    name: nexus-data